# Generated by Django 6.1 on 2026-08-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(help_text='Informe seu nome', max_length=50)),
                ('Email', models.CharField(help_text='Informe seu email', max_length=100)),
                ('DtaNas', models.DateField()),
            ],
        ),
    ]
